name: SMTPDOTCOM Webhook Config deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Type the version to deploy"
        required: true
        type: string

permissions: 
  checks: write
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      HELM_VERSION: v3.10.1
      HELM_CONFIG_PATH: "env/stitchedin/prod"
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Validate Tag
        run: |
          if ! git fetch --tags && git tag --list  | grep  "v.*" | grep "${{ github.event.inputs.tag }}"; then
            echo "Error: The tag '${{ github.event.inputs.tag }}' does not exist in the repository."
            exit 1
          fi

      - name: Test
        run: | 
          echo "Test"
          echo "${{ github.event.inputs.tag }}"
